paths:
  data_store: data
  logs: Logs
  log_file_name: logs
  artifacts: artifacts
  outputs: outputs
  
data_ingestion_config:
  dataset_name: 'xtreme'
  subset_name: 'PAN-X.en'

data_preprocessing:
  ner_tags:
    - O
    - B-PER
    - I-PER
    - B-ORG
    - I-ORG
    - B-LOC
    - I-LOC
data_validation_config:
  data_split:
    - train
    - test
    - validation
  
  columns_check:
    - tokens
    - ner_tags
    - langs

  type_check:
    - string # token
    - int64 # ner_tags
    - string # langs
    
base_model_config:
  base_model_name: xlm-roberta-base
  num_classes: 7
  num_epochs: 2
  batch_size: 16
  save_steps: 10000000